trigger: none

pool:
  vmImage: 'ubuntu-latest'
  name: personal
variables:
  imageName: "gtest-app"
  tag: "$(Build.BuildId)"
  acrLoginServer: "registry"
  namespace: "mock"

resources:
  repositories:
  - repository: g_test
    type: github
    endpoint: github.com_ericssontadashi
    name: ericssontadashi/g_test
    ref: main

stages:
- stage: Build
  displayName: "Build Docker Image"
  jobs:
    - job: Build
      displayName: "Build & Push Docker Image"
      steps:

      - checkout: g_test

      - task: DockerInstaller@0
        displayName: "Install Docker"

      - script: |
          echo "Building Docker image..."
          cd ./app
          docker build -t $(acrLoginServer)/$(imageName):$(tag) .
        displayName: "Docker Build"

      - script: |
          echo "Run unit tests"
        displayName: "Unit tests"

- stage: Trivy
  displayName: "Trivy step"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Trivy
    displayName: Trivy Scan

    steps:
    - checkout: g_test

    - script: |
        IMAGE=$(acrLoginServer)/$(imageName):$(tag)

        echo "Installing Trivy..."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sh -s -- -b /usr/local/bin

        echo "Running Trivy scan..."
        trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE
      displayName: Run Trivy Scan
      continueOnError: true

- stage: Checkov
  displayName: "Checkov step"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Checkov
    displayName: Checkov Scan
    steps:
    - checkout: g_test

    - script: |
        apt-get update
        apt-get install -y python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install checkov
        checkov --version
        checkov -d .
      displayName: "Install & Run Checkov"
      continueOnError: true

- stage: Deploy
  displayName: "Deploy to Kubernetes"
  dependsOn:
  - Trivy
  - Checkov
  condition: succeeded()
  jobs:
    - job: Deploy
      displayName: "Helm Deploy to Local Cluster"

      steps:
        - checkout: g_test

        - task: KubectlInstaller@0

        - task: HelmInstaller@1

        - bash: |
            kubectl cluster-info
          displayName: "Verify K8s Connection"

        - bash: |
            helm upgrade --install fastapi-comments ./chart \
              --set image.repository=$(acrLoginServer)/$(imageName) \
              --set image.tag=$(tag) --namespace $(namespace)
          displayName: "Helm Deploy"
